# Generated by Django 4.2.6 on 2023-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_state_post_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='archived',
            field=models.BooleanField(default=True),
        ),
    ]
