# Generated by Django 4.2.6 on 2023-11-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.BinaryField(),
        ),
    ]
