# Generated by Django 4.2.6 on 2023-12-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimages', to='main.post')),
            ],
        ),
    ]
